functions/api/routes/auth/authSignupPOST.js, functions/api/routes/auth/index.js, functions/api/routes/index.js, functions/constants/responseMessage.js, functions/db/index.js, functions/db/user.js, functions/lib/jwtHandlers.js
=> [FEAT] #2 - authSignupPOST

functions/api/routes/major/majorGET.js, functions/db/major.js
=> [FIX] #6 - majorGET 쿼리문 수정 및 함수명 수정

functions/api/routes/index.js, functions/api/routes/user/index.js, functions/api/routes/user/userMypageUserGET.js
=> [FEAT] #26 userMypageUserGET

functions/api/routes/index.js, functions/api/routes/like/index.js, functions/api/routes/like/likePOST.js, functions/constants/responseMessage.js, functions/db/like.js
=> [FEAT] #25 - likePOST

functions/api/routes/comment/commentDELETE.js, functions/api/routes/comment/index.js, functions/api/routes/index.js, functions/constants/responseMessage.js, functions/db/comment.js
=> [FEAT] #24 - commentDELETE

functions/api/routes/reviewPost/index.js, functions/api/routes/reviewPost/reviewPostPUT.js, functions/db/reviewPost.js
=> [FEAT] #11 - reviewPostPUT

functions/db/major.js
=> [FIX] #62 - majorGET rows -> rows[0] 수정

functions/api/routes/classroomPost/classroomPostInformationGET.js
=> [FIX] #67 - prevent no post from reading

functions/api/routes/reviewPost/reviewPostDetailGET.js, functions/api/routes/reviewPost/reviewPostPOST.js, functions/api/routes/reviewPost/reviewPostPUT.js, functions/db/reviewPost.js
* closed #71 
* 모든 reviewPost의 태그 순서 career 2번째 -> 4번째로 수정했습니다
=> [FIX] 태그 필터 순서 변경

functions/api/routes/classroomPost/classroomPostMajorListGET.js, functions/api/routes/classroomPost/index.js, functions/constants/responseMessage.js, functions/db/classroomPost.js, functions/db/comment.js
=> [FEAT] #17 - classroomPostMajorListGET

functions/api/routes/classroomPost/classroomPostPUT.js, functions/api/routes/classroomPost/index.js, functions/db/classroomPost.js, functions/db/comment.js
=> [FEAT] #20 classroomPostPUT

functions/api/routes/classroomPost/classroomPostPOST.js, functions/db/classroomPost.js
- functions/db/classroomPost.js 에서 createPost 함수 이름 createClassroomPost로 변경
=> [FIX] modify function name 

functions/api/routes/reviewPost/index.js, functions/api/routes/reviewPost/reviewPostListPOST.js, functions/db/relationReviewPostTag.js, functions/db/reviewPost.js
=> [FEAT] #8 reviewPostListPOST

functions/api/routes/major/majorListGET.js, functions/db/major.js
* closed #60 
* #7 
* #33 
* 이중전공인 학과 목록들 가져올 때 제 1전공이 아니고 2전공인 것들만 가져오는 오류 수정하였습니다.
* 학과 목록 가져올 때 major_id 오름차순으로 가져오도록 order by 추가하였습니다.
=> [FIX] #60 - majorListGET 이중 전공 리스트 가져올 때 제1전공 false로 가져오던 오류 수정

functions/api/routes/classroomPost/classroomPostQuestionGET.js, functions/api/routes/classroomPost/index.js
=> [FEAT] #42 - classroomPostQuestionGET

functions/api/routes/auth/authSignupPOST.js, functions/db/user.js, functions/package-lock.json, functions/package.json
=> [FEAT] #74 profile_image_id random generation

functions/api/routes/auth/authDuplicationCheckEmailPOST.js, functions/api/routes/auth/index.js, functions/constants/responseMessage.js, functions/db/user.js
=> [FEAT] #4 - authDuplicationCheckEmailPOST

functions/api/routes/auth/authLoginPOST.js, functions/constants/responseMessage.js, functions/db/user.js
=> [FEAT] #82 - login에 device token 업데이트 추가

functions/api/routes/auth/authLoginPOST.js
=> [FEAT] #84 - login 리스폰스에 major id 추가

functions/api/routes/index.js, functions/api/routes/notification/index.js, functions/api/routes/notification/notificationListGET.js
=> [FEAT] #88 - notificationListGET

functions/api/routes/notification/notificationReadPUT.js
=> [FEAT]#89 - notificationReadPUT

functions/api/routes/comment/commentPOST.js
=> [FIX] #103 - commentPOST 푸시알림 multicast error

functions/api/routes/comment/commentPOST.js
=> [FIX] #103 - 푸시 알림 multicast error

functions/api/routes/reviewPost/reviewPostListPOST.js
=> [FIX] #109 - 후기 목록 가져올 때 postid 오류 수정

functions/middlewares/slackAPI.js
=> [FEAT] #120 middleware에 slackAPI 추가

functions/api/routes/classroomPost/classroomPostDELETE.js, functions/api/routes/classroomPost/classroomPostInformationGET.js, functions/api/routes/classroomPost/classroomPostMajorListGET.js, functions/api/routes/classroomPost/classroomPostPOST.js, functions/api/routes/classroomPost/classroomPostPUT.js, functions/api/routes/classroomPost/classroomPostQuestionGET.js
=> [FEAT] #112 add SlackAPI to classroomPost/

functions/api/routes/like/likePOST.js
=> [FEAT] # 114 add SlackAPI to like/

functions/api/routes/comment/commentDELETE.js, functions/api/routes/comment/commentPOST.js, functions/api/routes/comment/commentPUT.js
=> [FEAT] #113 add SlackAPI to comment/

functions/api/routes/major/majorGET.js, functions/api/routes/major/majorListGET.js
=> [FEAT] #115 add SlackAPI to major/

functions/api/routes/notification/notificationDELETE.js, functions/api/routes/notification/notificationListGET.js, functions/api/routes/notification/notificationReadPUT.js
=> [FEAT] #116 add SlackAPI to notification/

functions/api/routes/report/reportCommentPOST.js, functions/api/routes/report/reportPostPOST.js, functions/api/routes/report/reportUserPOST.js
=> [FEAT] #117 add SlackAPI to report/

functions/api/routes/reviewPost/reviewPostBackgroundImageListGET.js, functions/api/routes/reviewPost/reviewPostDELETE.js, functions/api/routes/reviewPost/reviewPostDetailGET.js, functions/api/routes/reviewPost/reviewPostListPOST.js, functions/api/routes/reviewPost/reviewPostPOST.js, functions/api/routes/reviewPost/reviewPostPUT.js, functions/api/routes/reviewPost/reviewPostTagListGET.js
=> [FEAT] #118 add SlackAPI to reviewPost/

functions/db/notification.js
=> [FEAT] #138 - 알림 리스트 가져올 때 최신순 정렬 쿼리 추가

functions/api/routes/reviewPost/reviewPostPOST.js, functions/db/user.js
=> [FIX] add error handling when creating review post

functions/api/routes/classroomPost/classroomPostInformationGET.js, functions/api/routes/classroomPost/classroomPostMajorListGET.js, functions/api/routes/classroomPost/classroomPostPUT.js, functions/api/routes/classroomPost/classroomPostQuestionGET.js
=> [FIX] fix count to number type

functions/api/routes/reviewPost/reviewPostDetailGET.js, functions/api/routes/reviewPost/reviewPostListPOST.js, functions/api/routes/reviewPost/reviewPostPUT.js
=> [FIX] #140 fix likeCount to integer value

functions/api/routes/classroomPost/classroomPostPOST.js, functions/api/routes/comment/commentPOST.js
=> [FEAT] #145 - 푸시알림에 소리 추가

functions/api/routes/major/majorListGET.js, functions/db/major.js
=> [REFACTOR] #76 - 쿼리문 하나로 줄이기

functions/api/routes/user/userListMajorGET.js
=> [FIX] user list 랜덤으로 정렬

functions/api/routes/reviewPost/reviewPostDELETE.js
=> [FEAT] #161 - 후기삭제 response에 isReviewed 추가

functions/api/routes/auth/authUniversityGET.js, functions/api/routes/auth/index.js, functions/constants/responseMessage.js, functions/db/index.js, functions/db/university.js
=> [FEAT] #160 - 해당 학교 이메일 조회 구현

functions/api/routes/auth/authLoginPOST.js
=> [FEAT] #166 - 로그인에 isEmailVerified 추가

functions/api/routes/reviewPost/reviewPostDELETE.js
=> [REFACTOR] 모든 int형 재검토

functions/api/routes/classroomPost/classroomPostPOST.js, functions/api/routes/comment/commentPOST.js, functions/api/routes/notification/notificationListGET.js, functions/db/notification.js
=> [FEAT] 삭제된 글, 댓글의 경우 알림리스트 처리

functions/api/routes/classroomPost/classroomPostMajorListGET.js, functions/api/routes/reviewPost/reviewPostListPOST.js, functions/api/routes/user/userMypageClassroomPostListGET.js
=> [FEAT] add isLiked, refactor post type

functions/api/routes/user/index.js, functions/api/routes/user/userMypageCommentListGET.js, functions/db/classroomPost.js, functions/db/comment.js
=> [FEAT] #172 - userMypageCommentListGET

functions/api/routes/auth/authSignupPOST.js
**매일 보내는 것을 res 보낸 후로 변경했습니다. (메일이 제대로 보내지지 않아도 재전송 할 수 있는 버튼이 바로 뒤에 나오기 때문)**
* 오히려 회원가입은 잘 되고, 메일 보내기만 안 된 경우 회원가입을 처음부터 진행해야 하는 문제가 발생할 수 있음.
* 메일 보내기에 error처리를 안한 건 res를 만나고 메일 전송에서 오류가 발생하면 res 중복 문제가 발생함.
=> [REFACTOR] #213 - 회원가입 속도 개선

functions/api/routes/block/blockPOST.js, functions/api/routes/block/index.js, functions/api/routes/index.js, functions/constants/responseMessage.js, functions/db/block.js, functions/db/index.js
=> [FEAT] #206 - blockPOST

functions/api/routes/classroomPost/classroomPostMajorListGET.js, functions/api/routes/reviewPost/reviewPostListPOST.js, functions/api/routes/user/userMypageClassroomPostListGET.js
=> [FIX] fix like sorting

functions/api/routes/user/index.js, functions/api/routes/user/userMypageReviewPostListGET.js
=> [REFACTOR] get others mypage review post list

functions/api/routes/user/index.js, functions/api/routes/user/userMypageCommentListGET.js, functions/db/comment.js
=> [FEAT] #202 - userMypageCommentListGET

functions/api/routes/notification/notificationListGET.js
=> [STYLE] 알림 리스트에서 원본글이나 댓글이 삭제됐을 경우 워딩 변경

functions/api/routes/block/blockListGET.js, functions/api/routes/block/index.js, functions/constants/responseMessage.js, functions/db/block.js
=> [FEAT] #207 - blockListGET

functions/api/routes/user/userMypagePUT.js, functions/db/user.js
=> [FIX] #226 - 마이페이지 닉네임 관련 분기 처리 추가

functions/api/routes/classroomPost/classroomPostPOST.js, functions/api/routes/comment/commentPOST.js, functions/db/comment.js, functions/db/user.js, functions/lib/pushAlarmHandlers.js
- closed #220
- 은지 언니 거 보면서 정말 많이 배움,,! 이것은 제가 마지막으로 정리했지만 언니와 나의 합작물,, ✨
- 해당 PR 머지되면 디바이스 토큰이 없는 유저의 토큰은 받지 않도록 하는 코드도 따로 구현하겠습니다! (그건 버그로 이슈를 따로 팠음)
=> [REFACTOR] 알림 리펙토링

functions/db/classroomPost.js, functions/db/comment.js, functions/db/notification.js, functions/db/relationReviewPostTag.js, functions/db/report.js, functions/db/reviewPost.js, functions/db/tag.js, functions/db/user.js
=> [STYLE] #248 - 쿼리 TRUE, FALSE 수정 

functions/api/routes/classroomPost/classroomPostPOST.js, functions/api/routes/comment/commentPOST.js, functions/api/routes/reviewPost/reviewPostDetailGET.js, functions/api/routes/reviewPost/reviewPostPUT.js
=> [REFACTOR] get post type from constants

functions/api/routes/notification/notificationReadPUT.js, functions/db/notification.js
=> [FEAT] read all notification when post id, receiver id is same

functions/api/routes/classroomPost/classroomPostMajorListGET.js, functions/api/routes/major/majorListGET.js, functions/api/routes/report/reportPUT.js, functions/api/routes/reviewPost/reviewPostBackgroundImageListGET.js, functions/api/routes/reviewPost/reviewPostListPOST.js, functions/api/routes/user/userMypageCommentListGET.js, functions/api/routes/user/userMypageReviewPostListGET.js
=> [FIX] fix conditional statement when list empty

functions/api/routes/reviewPost/reviewPostListPOST.js, functions/db/reviewPost.js
* closed #208 
후기 리스트에 차단 유저 안보이게 고쳤습니다옹
=> [FEAT] #208 - add block to reviewpost list get

functions/api/routes/classroomPost/classroomPostQuestionGET.js
=> [FIX] #258 - 질문글 상세 조회 createdAt -> updatedAt 수정

functions/api/routes/reviewPost/reviewPostListPOST.js, functions/db/reviewPost.js
=> [FIX] fix created at to review post timestamp

functions/api/routes/auth/authLoginPOST.js, functions/api/routes/classroomPost/classroomPostInformationGET.js, functions/api/routes/classroomPost/classroomPostPOST.js, functions/api/routes/classroomPost/classroomPostQuestionGET.js, functions/api/routes/inappropriateReviewPost/inappropriateReviewPostPOST.js, functions/api/routes/inappropriateReviewPost/index.js, functions/api/routes/index.js, functions/api/routes/reviewPost/reviewPostDELETE.js, functions/api/routes/reviewPost/reviewPostDetailGET.js, functions/api/routes/reviewPost/reviewPostPOST.js, functions/constants/responseMessage.js, functions/db/inappropriateReviewPost.js, functions/db/index.js, functions/db/reviewPost.js, functions/middlewares/auth.js
=> [FEAT] 부적절 후기

functions/api/routes/notification/notificationDELETE.js, functions/api/routes/notification/notificationListGET.js
=> [FIX] notification error handling

functions/api/routes/auth/authLoginPOST.js
=> [FIX] #275 - authLoginPOST에 예외 처리 추가

functions/api/routes/auth/authSecessionPOST.js, functions/api/routes/classroomPost/classroomPostDELETE.js, functions/api/routes/notification/notificationReadPUT.js, functions/api/routes/report/reportPUT.js, functions/api/routes/reviewPost/reviewPostDELETE.js, functions/api/routes/user/userListMajorGET.js, functions/api/routes/user/userMypageReviewPostListGET.js, functions/db/block.js, functions/db/classroomPost.js, functions/db/comment.js, functions/db/like.js, functions/db/notification.js, functions/db/relationReviewPostTag.js, functions/db/report.js, functions/db/reviewPost.js, functions/db/user.js
=> [FEAT] 리스트 정렬 및 rows 반환되는 리스트 워딩 수정

functions/api/routes/auth/authLogoutPOST.js, functions/db/user.js
=> [FIX] remove deviceToken

functions/api/routes/classroomPost/classroomPostInformationGET.js, functions/api/routes/classroomPost/classroomPostPOST.js, functions/api/routes/classroomPost/classroomPostQuestionGET.js, functions/api/routes/reviewPost/reviewPostDetailGET.js, functions/api/routes/reviewPost/reviewPostPOST.js
=> [FIX] #286 - fix bug at report code

functions/api/routes/classroomPost/classroomPostMajorListGET.js, functions/api/routes/report/reportPUT.js, functions/api/routes/reviewPost/reviewPostDELETE.js, functions/api/routes/reviewPost/reviewPostPUT.js, functions/api/routes/user/userMypageClassroomPostListGET.js, functions/constants/responseMessage.js
=> [REFACTOR] refactor response message

functions/api/routes/block/index.js, functions/api/routes/major/index.js, functions/api/routes/notification/index.js, functions/api/routes/post/index.js, functions/api/routes/review/index.js, functions/api/routes/user/index.js
- #305 
- list가 달려있는 모든 엔드포인트 list 삭제하는 것으로 refactor
- 파일명 및 디비 쿼리명은 변경하지 않음
=> refactor: fix routing

.firebaserc, .gitignore, functions/middlewares/slackAPI.js, functions/package.json
- closes #311
`.env`
`.env.local`
`.env.dev`
`.env.prod`
모두 슬랙으로 다시 드릴테니 반영해주세요
=> check process.env.NODE_ENV 

functions/api/routes/user/userMypagePUT.js, functions/db/user.js
=> mypage put

.gitignore, functions/api/routes/review/index.js, functions/api/routes/review/reviewUniversityListGET.js, functions/db/review.js
- #308 
- git ignore 중복 변수 지움
- reviewMajorListGET index에도 major 추가 
- 이 부분은 어차피 GET통신으로 바꾸면 붙을 부분이기 때문에 미리 파일명 따라 바꿨습니다.
- like도 tag와 같은 이유로 반영 안 하기로 했어서 json_build_object 함수 지웠습니다.
- DB 쿼리에 is_deleted major에도 필요할 것 같아서 추가했습니다.
---
원래는 DB column 바뀐 거 이해하기 혼란스러울까봐 직접하려고 시작했는데, 사소한 수정만 했네요! 언제 다 팔로업하셨져,, 👍
얘 먼저 확인해주시고 머지한 담에는 바로 #308도 머지하면 될 것 같아요
=> apply change

functions/api/routes/auth/authUniversityGET.js, functions/api/routes/major/majorGET.js, functions/api/routes/user/userMypageReviewListGET.js, functions/constants/responseMessage.js
- closes #326
- 별도 status 없이 빈 배열로 보내는 것이 더 깔끔하다 판단하여 수정하기로 함
- major 정보나 university email이 없는 경우는 실패 response로 전환
클라에 전달 필요함
=> delete send 204 status code

functions/api/routes/user/userListMajorGET.js, functions/api/routes/user/userMypageGET.js, functions/db/post.js, functions/db/user.js
- closes #343
- 마이페이지 받은 1:1질문 없을 때 null로 표기
---
- 응답률 기준 정렬
- 후기 작성한 선배만 보기 exclude === "noReview" query로 구현. exclude가 다른 값으로 들어올 경우 별도 처리 하지 않고 전체 내보냄
=> user major list

functions/api/routes/post/postPOST.js, functions/api/routes/post/postPUT.js
- closes #324 
- 커뮤티니와 1:1 질문에서 모두 사용할 수 있게 했습니다. (type 자유게시판 추가)
- post PUT refactor
=> create post, update post

functions/api/routes/app/versionRecentGET.js, functions/constants/appVersion.js
- closes #353 
`.env에 VERSION_AOS=1.1.3 VERSION_iOS=1.1.1 추가해주세요`
=> load app version from env

functions/api/routes/post/postListGET.js, functions/db/post.js
=> implement post search

functions/api/routes/post/index.js, functions/api/routes/post/postListGET.js, functions/db/post.js
- 검색어 없을 때 전체 검색 기능
- university 검색 추가
=> fix post list

functions/api/routes/app/bannerListGET.js, functions/api/routes/app/index.js, functions/db/image.js
closed #366 
- 이미지 DB에 type 컬럼 추가 후 iOS, AOS를 넣어주었습니다.
=> separate banner image

functions/api/routes/post/postGET.js
closed #369 
1:1 채팅 뷰 하단의 플로팅 버튼 분기 처리를 위해 req.user.id가 작성자/답변자에 해당하는지 확인합니다.
=> add isAuthorized to postGET res

functions/api/routes/auth/authLoginPOST.js
closed #365 
로그인 response에 updateAlert 문구를 넣습니다.
=> add update alert text to login res

functions/api/routes/post/postGET.js
=> add type check

functions/api/routes/app/bannerListGET.js, functions/db/banner.js, functions/db/index.js
- closes #374
- type, redirect url 등이 추가된 DB는 공용 image DB로 사용하긴 어려울 것이라 판단해 bannerDB로 수정했습니다.
- redirect url 추가하여 res가 string array에서 object array로 변경되었습니다
---
=> rename banner, add redirect url

functions/api/routes/comment/commentPOST.js
=> fix comment notification message

functions/api/routes/review/reviewMajorListGET.js, functions/db/review.js
- closes #372 
- console log 지우고, like list 관련하여 refactor 진행했습니다. reviewUniversityList와 최대한 동일한 형식으로 수정했습니다.
=> refactor review major db query

functions/db/review.js
=> fix error review major list

functions/api/routes/auth/index.js, functions/api/routes/block/index.js, functions/api/routes/comment/index.js, functions/api/routes/favorites/index.js, functions/api/routes/inappropriateReview/index.js, functions/api/routes/like/index.js, functions/api/routes/major/index.js, functions/api/routes/notification/index.js, functions/api/routes/post/index.js, functions/api/routes/report/index.js, functions/api/routes/review/index.js, functions/api/routes/user/index.js
closed #382 
number type인 프로퍼티들 타입 수정해주었습니다.
=> fix swaager type (string to number)

functions/db/post.js
쿼리에 answererId가 없어서 undefined로 나와서 결론적으로 답변자임에도 불구하고 isAutorized가 false로 나오는 오류 수정
=> add answererId to post detail query

functions/api/routes/post/index.js, functions/config/firebaseClient.js, functions/package.json
*closed #384 
- firebase key를 .env에 넣었습니다.
- package.json에 필요없는 swagger 관련 코드를 삭제하였습니다.
- 스웨거 설명 오류 수정하였습니다 (1:1 질문, 전체에게 질문 바껴있었음)
=> hide firebase key

functions/api/routes/major/index.js, functions/api/routes/notification/notificationListGET.js, functions/api/routes/post/index.js, functions/db/notification.js
closed #389 
* 알림 리스트 조회에서 전체에게 질문일 경우 (noti type id가 10인 경우) sender에 학과 데이터를 넣습니다.
* nickname -> senderName으로 변경했습니다.
* 스웨거 주석 오류 수정했습니다.
=> change notification sender id when question to everyone

functions/api/routes/user/userPostQuestionListGET.js, functions/db/post.js
=> feat: add is authorized

functions/api/routes/user/userPUT.js
=> fix: delete bio null exception

functions/middlewares/slackAPI.js
- local 및 development 환경은 슬랙 알럿이 가지 않도록 수정
=> fix: slack alert only when production env

functions/api/routes/comment/commentPOST.js
* qa 중 1:1 댓글 알람이 가지 않는 오류를 수정하였습니다.
=> [FIX] fix 1:1 push alarm

functions/lib/jwtHandlers.js
* accessToken 클라 확인 완료되어서 다시 3h로 변경했습니다
=> [CHORE] change access token expiresIn

functions/api/routes/post/postUniversityListGET.js, functions/db/post.js
* 답변자의 모든 학과에서 떠야하지만 하나의 학과에서만 나타나는 문제를 해결했습니다.
예를 들어, 본전공 디지털미디어학과, 복수전공 소프트웨어융합학과인경우
과방의 1:1질문에서 디미, 소융에 모두 해당 글이 떠야합니다.
=> [HOTFIX] fix get questionToPerson List

functions/api/routes/post/postPOST.js
* 더미 메세지 유저 범위 수정
* 더미 메세지 내용 수정
=> [CHORE] fix dummy slack message
